#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Check coade complexity eith lizard.
if which lizard>/dev/null; then
    if lizard -w  -m --sort cyclomatic_complexity --CCN 10 --arguments 9 --length 100 -T nloc=100 $(git diff --cached --name-only $against | egrep '\.cc|\.h'); then
	exit 0
    else
	exit 1
    fi
else
    cat <<\EOF
Please download the lizard app (https://github.com/terryyin/lizard.git)
and place the executable in your PATH.
EOF
    exit 1
fi

